# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addFlightNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_addFlightNote(QDialog):
    def setupUi(self, addFlightNote):
        addFlightNote.setObjectName("addFlightNote")
        addFlightNote.resize(640, 480)
        addFlightNote.setStyleSheet("QDialog{\n"
"background-color: #707070;\n"
"border-radius: 5px;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(addFlightNote)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.departureDateEdit = QtWidgets.QDateEdit(addFlightNote)
        self.departureDateEdit.setObjectName("departureDateEdit")
        self.gridLayout.addWidget(self.departureDateEdit, 1, 0, 1, 1)
        self.downtimeEdit = QtWidgets.QLineEdit(addFlightNote)
        self.downtimeEdit.setObjectName("downtimeEdit")
        self.gridLayout.addWidget(self.downtimeEdit, 1, 1, 1, 1)
        self.arrivalDate = QtWidgets.QLabel(addFlightNote)
        self.arrivalDate.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.arrivalDate.setObjectName("arrivalDate")
        self.gridLayout.addWidget(self.arrivalDate, 2, 0, 1, 1)
        self.driversFullName = QtWidgets.QLabel(addFlightNote)
        self.driversFullName.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.driversFullName.setObjectName("driversFullName")
        self.gridLayout.addWidget(self.driversFullName, 2, 1, 1, 1)
        self.downtime = QtWidgets.QLabel(addFlightNote)
        self.downtime.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.downtime.setObjectName("downtime")
        self.gridLayout.addWidget(self.downtime, 0, 1, 1, 1)
        self.arrivalDateEdit = QtWidgets.QDateEdit(addFlightNote)
        self.arrivalDateEdit.setObjectName("arrivalDateEdit")
        self.gridLayout.addWidget(self.arrivalDateEdit, 3, 0, 1, 1)
        self.departurePoint = QtWidgets.QLabel(addFlightNote)
        self.departurePoint.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.departurePoint.setObjectName("departurePoint")
        self.gridLayout.addWidget(self.departurePoint, 4, 0, 1, 1)
        self.driversSalary = QtWidgets.QLabel(addFlightNote)
        self.driversSalary.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.driversSalary.setObjectName("driversSalary")
        self.gridLayout.addWidget(self.driversSalary, 4, 1, 1, 1)
        self.departurePointEdit = QtWidgets.QLineEdit(addFlightNote)
        self.departurePointEdit.setObjectName("departurePointEdit")
        self.gridLayout.addWidget(self.departurePointEdit, 5, 0, 1, 1)
        self.driversSalaryEdit = QtWidgets.QLineEdit(addFlightNote)
        self.driversSalaryEdit.setObjectName("driversSalaryEdit")
        self.gridLayout.addWidget(self.driversSalaryEdit, 5, 1, 1, 1)
        self.departureDate = QtWidgets.QLabel(addFlightNote)
        self.departureDate.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.departureDate.setObjectName("departureDate")
        self.gridLayout.addWidget(self.departureDate, 0, 0, 1, 1)
        self.driversFullNameEdit = QtWidgets.QLineEdit(addFlightNote)
        self.driversFullNameEdit.setObjectName("driversFullNameEdit")
        self.gridLayout.addWidget(self.driversFullNameEdit, 3, 1, 1, 1)
        self.fuelConsumption = QtWidgets.QLabel(addFlightNote)
        self.fuelConsumption.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.fuelConsumption.setObjectName("fuelConsumption")
        self.gridLayout.addWidget(self.fuelConsumption, 6, 1, 1, 1)
        self.arrivalPoint = QtWidgets.QLabel(addFlightNote)
        self.arrivalPoint.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.arrivalPoint.setObjectName("arrivalPoint")
        self.gridLayout.addWidget(self.arrivalPoint, 6, 0, 1, 1)
        self.fuelConsumptionEdit = QtWidgets.QLineEdit(addFlightNote)
        self.fuelConsumptionEdit.setObjectName("fuelConsumptionEdit")
        self.gridLayout.addWidget(self.fuelConsumptionEdit, 7, 1, 1, 1)
        self.priceEdit = QtWidgets.QLineEdit(addFlightNote)
        self.priceEdit.setObjectName("priceEdit")
        self.gridLayout.addWidget(self.priceEdit, 9, 0, 1, 1)
        self.price = QtWidgets.QLabel(addFlightNote)
        self.price.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 8, 0, 1, 1)
        self.acceptButton = QtWidgets.QPushButton(addFlightNote)
        self.acceptButton.setStyleSheet("QPushButton{\n"
"    color: #FAFAFA;\n"
"    background-color: #939393;\n"
"    border-radius:6px;\n"
"    height: 25px;\n"
"    font: 10pt \"Comfortaa\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #888888;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #888888;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/save/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acceptButton.setIcon(icon)
        self.acceptButton.setObjectName("acceptButton")
        self.gridLayout.addWidget(self.acceptButton, 10, 0, 1, 1)
        self.rejectButton = QtWidgets.QPushButton(addFlightNote)
        self.rejectButton.setStyleSheet("QPushButton{\n"
"    color: #FAFAFA;\n"
"    background-color: #939393;\n"
"    border-radius:6px;\n"
"    height: 25px;\n"
"    font: 10pt \"Comfortaa\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #888888;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #888888;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cancel/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rejectButton.setIcon(icon1)
        self.rejectButton.setObjectName("rejectButton")
        self.gridLayout.addWidget(self.rejectButton, 10, 1, 1, 1)
        self.additionalExpensesEdit = QtWidgets.QLineEdit(addFlightNote)
        self.additionalExpensesEdit.setObjectName("additionalExpensesEdit")
        self.gridLayout.addWidget(self.additionalExpensesEdit, 9, 1, 1, 1)
        self.arrivalPointEdit = QtWidgets.QLineEdit(addFlightNote)
        self.arrivalPointEdit.setObjectName("arrivalPointEdit")
        self.gridLayout.addWidget(self.arrivalPointEdit, 7, 0, 1, 1)
        self.additionalExpenses = QtWidgets.QLabel(addFlightNote)
        self.additionalExpenses.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.additionalExpenses.setObjectName("additionalExpenses")
        self.gridLayout.addWidget(self.additionalExpenses, 8, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(addFlightNote)
        QtCore.QMetaObject.connectSlotsByName(addFlightNote)

    def retranslateUi(self, addFlightNote):
        _translate = QtCore.QCoreApplication.translate
        addFlightNote.setWindowTitle(_translate("addFlightNote", "Dialog"))
        self.arrivalDate.setText(_translate("addFlightNote", "Дата выгрузки "))
        self.driversFullName.setText(_translate("addFlightNote", "ФИО водителя"))
        self.downtime.setText(_translate("addFlightNote", "Простой загрузки"))
        self.departurePoint.setText(_translate("addFlightNote", "Точка загрузки"))
        self.driversSalary.setText(_translate("addFlightNote", "Зарплата водителя"))
        self.departureDate.setText(_translate("addFlightNote", "Дата загрузки"))
        self.fuelConsumption.setText(_translate("addFlightNote", "Топливо"))
        self.arrivalPoint.setText(_translate("addFlightNote", "Точка выгрузки"))
        self.price.setText(_translate("addFlightNote", "Цена загрузки"))
        self.acceptButton.setText(_translate("addFlightNote", "Сохранить"))
        self.rejectButton.setText(_translate("addFlightNote", "Отмена"))
        self.additionalExpenses.setText(_translate("addFlightNote", "Доп. траты"))
import ui.icons
