# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editFlightNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_editFlightNote(QDialog):
    def setupUi(self, editFlightNote):
        editFlightNote.setObjectName("editFlightNote")
        editFlightNote.resize(640, 479)
        editFlightNote.setStyleSheet("QDialog{\n"
"background-color: #707070;\n"
"border-radius: 5px;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(editFlightNote)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.driversSalaryEdit = QtWidgets.QLineEdit(editFlightNote)
        self.driversSalaryEdit.setObjectName("driversSalaryEdit")
        self.gridLayout.addWidget(self.driversSalaryEdit, 7, 1, 1, 1)
        self.fuelConsumptionEdit = QtWidgets.QLineEdit(editFlightNote)
        self.fuelConsumptionEdit.setObjectName("fuelConsumptionEdit")
        self.gridLayout.addWidget(self.fuelConsumptionEdit, 9, 1, 1, 1)
        self.flightStatusLabel = QtWidgets.QLabel(editFlightNote)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.flightStatusLabel.setFont(font)
        self.flightStatusLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.flightStatusLabel.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.flightStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.flightStatusLabel.setObjectName("flightStatusLabel")
        self.gridLayout.addWidget(self.flightStatusLabel, 0, 0, 1, 2)
        self.departurePoint = QtWidgets.QLabel(editFlightNote)
        self.departurePoint.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.departurePoint.setObjectName("departurePoint")
        self.gridLayout.addWidget(self.departurePoint, 6, 0, 1, 1)
        self.departurePointEdit = QtWidgets.QLineEdit(editFlightNote)
        self.departurePointEdit.setObjectName("departurePointEdit")
        self.gridLayout.addWidget(self.departurePointEdit, 7, 0, 1, 1)
        self.arrivalDate = QtWidgets.QLabel(editFlightNote)
        self.arrivalDate.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.arrivalDate.setObjectName("arrivalDate")
        self.gridLayout.addWidget(self.arrivalDate, 4, 0, 1, 1)
        self.driversFullNameEdit = QtWidgets.QLineEdit(editFlightNote)
        self.driversFullNameEdit.setObjectName("driversFullNameEdit")
        self.gridLayout.addWidget(self.driversFullNameEdit, 5, 1, 1, 1)
        self.departureDate = QtWidgets.QLabel(editFlightNote)
        self.departureDate.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.departureDate.setObjectName("departureDate")
        self.gridLayout.addWidget(self.departureDate, 2, 0, 1, 1)
        self.downtimeEdit = QtWidgets.QLineEdit(editFlightNote)
        self.downtimeEdit.setObjectName("downtimeEdit")
        self.gridLayout.addWidget(self.downtimeEdit, 3, 1, 1, 1)
        self.driversFullName = QtWidgets.QLabel(editFlightNote)
        self.driversFullName.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.driversFullName.setObjectName("driversFullName")
        self.gridLayout.addWidget(self.driversFullName, 4, 1, 1, 1)
        self.downtime = QtWidgets.QLabel(editFlightNote)
        self.downtime.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.downtime.setObjectName("downtime")
        self.gridLayout.addWidget(self.downtime, 2, 1, 1, 1)
        self.idSpinBox = QtWidgets.QSpinBox(editFlightNote)
        self.idSpinBox.setMaximum(100000)
        self.idSpinBox.setObjectName("idSpinBox")
        self.gridLayout.addWidget(self.idSpinBox, 1, 0, 1, 2)
        self.fuelConsumption = QtWidgets.QLabel(editFlightNote)
        self.fuelConsumption.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.fuelConsumption.setObjectName("fuelConsumption")
        self.gridLayout.addWidget(self.fuelConsumption, 8, 1, 1, 1)
        self.arrivalPointEdit = QtWidgets.QLineEdit(editFlightNote)
        self.arrivalPointEdit.setObjectName("arrivalPointEdit")
        self.gridLayout.addWidget(self.arrivalPointEdit, 9, 0, 1, 1)
        self.arrivalPoint = QtWidgets.QLabel(editFlightNote)
        self.arrivalPoint.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.arrivalPoint.setObjectName("arrivalPoint")
        self.gridLayout.addWidget(self.arrivalPoint, 8, 0, 1, 1)
        self.driversSalary = QtWidgets.QLabel(editFlightNote)
        self.driversSalary.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.driversSalary.setObjectName("driversSalary")
        self.gridLayout.addWidget(self.driversSalary, 6, 1, 1, 1)
        self.additionalExpensesEdit = QtWidgets.QLineEdit(editFlightNote)
        self.additionalExpensesEdit.setObjectName("additionalExpensesEdit")
        self.gridLayout.addWidget(self.additionalExpensesEdit, 11, 1, 1, 1)
        self.acceptButton = QtWidgets.QPushButton(editFlightNote)
        self.acceptButton.setStyleSheet("QPushButton{\n"
"    color: #FAFAFA;\n"
"    background-color: #939393;\n"
"    border-radius:6px;\n"
"    height: 25px;\n"
"    font: 10pt \"Comfortaa\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #888888;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #888888;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/save/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acceptButton.setIcon(icon)
        self.acceptButton.setObjectName("acceptButton")
        self.gridLayout.addWidget(self.acceptButton, 12, 0, 1, 1)
        self.priceEdit = QtWidgets.QLineEdit(editFlightNote)
        self.priceEdit.setObjectName("priceEdit")
        self.gridLayout.addWidget(self.priceEdit, 11, 0, 1, 1)
        self.price = QtWidgets.QLabel(editFlightNote)
        self.price.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 10, 0, 1, 1)
        self.additionalExpenses = QtWidgets.QLabel(editFlightNote)
        self.additionalExpenses.setStyleSheet("color: #FAFAFA;\n"
"font: 15pt \"Comfortaa\";")
        self.additionalExpenses.setObjectName("additionalExpenses")
        self.gridLayout.addWidget(self.additionalExpenses, 10, 1, 1, 1)
        self.rejectButton = QtWidgets.QPushButton(editFlightNote)
        self.rejectButton.setStyleSheet("QPushButton{\n"
"    color: #FAFAFA;\n"
"    background-color: #939393;\n"
"    border-radius:6px;\n"
"    height: 25px;\n"
"    font: 10pt \"Comfortaa\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #888888;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #888888;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cancel/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rejectButton.setIcon(icon1)
        self.rejectButton.setObjectName("rejectButton")
        self.gridLayout.addWidget(self.rejectButton, 12, 1, 1, 1)
        self.departureDateEdit = QtWidgets.QDateEdit(editFlightNote)
        self.departureDateEdit.setObjectName("departureDateEdit")
        self.gridLayout.addWidget(self.departureDateEdit, 3, 0, 1, 1)
        self.arrivalDateEdit = QtWidgets.QDateEdit(editFlightNote)
        self.arrivalDateEdit.setObjectName("arrivalDateEdit")
        self.gridLayout.addWidget(self.arrivalDateEdit, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(editFlightNote)
        QtCore.QMetaObject.connectSlotsByName(editFlightNote)

    def retranslateUi(self, editFlightNote):
        _translate = QtCore.QCoreApplication.translate
        editFlightNote.setWindowTitle(_translate("editFlightNote", "Dialog"))
        self.flightStatusLabel.setText(_translate("editFlightNote", "Введите ID искомой записи"))
        self.departurePoint.setText(_translate("editFlightNote", "Точка загрузки"))
        self.arrivalDate.setText(_translate("editFlightNote", "Дата выгрузки"))
        self.departureDate.setText(_translate("editFlightNote", "Дата загрузки"))
        self.driversFullName.setText(_translate("editFlightNote", "ФИО водителя"))
        self.downtime.setText(_translate("editFlightNote", "Простой загрузки"))
        self.fuelConsumption.setText(_translate("editFlightNote", "Топливо"))
        self.arrivalPoint.setText(_translate("editFlightNote", "Точка выгрузки"))
        self.driversSalary.setText(_translate("editFlightNote", "Зарплата водителя"))
        self.acceptButton.setText(_translate("editFlightNote", "Сохранить"))
        self.price.setText(_translate("editFlightNote", "Цена загрузки"))
        self.additionalExpenses.setText(_translate("editFlightNote", "Доп. траты"))
        self.rejectButton.setText(_translate("editFlightNote", "Отмена"))
import ui.icons
